### PR TITLE
[Subresource] Make the generated code working with v1.12 

### LINKED ISSUE #298: create subresource is not working because of  interface Incompatibility between old version and v1.12
The error is like 
```
cannot use xxREST literal (type *xxREST) as type rest.CreaterUpdater in assignment:
	*xxREST does not implement rest.CreaterUpdater (wrong type for Create method)
		have Create(context.Context, runtime.Object, rest.ValidateObjectFunc, bool) (runtime.Object, error)
		want Create(context.Context, runtime.Object, rest.ValidateObjectFunc, *v1.CreateOptions) (runtime.Object, error)
```
occurred both in `CreaterUpdater`  and `Patcher`

### PR DESCRIPTION
**Pull request by magicsong**
fix #298

### CODE REVIEW

**Comment by yue9944882** [comment]
@magicsong thx for fixing this! please squash otherwise lgtm

**Comment by magicsong** [comment]
@yue9944882 thank you for reviewing my code! it is one commit now.
